### ISSUE TITLE
Repo future and maintanance

### ISSUE THREAD

**Issue by igoras1993** [RupamSolanki/py_api_saga#3]
Hi!

Me and my team currently are looking for some approaches to the good microservices practices. Your work looks promising. I have a question - what are Your plans for the future of this project? Are You eager to maintain it/adding new feats when needed? Are You looking some help in maintaining the project?

**Comment by RupamSolanki** [comment]
Hello @igoras1993  I have some ideas for improving the logic and making it more optimized. Yes, I will include additional features as they are required.  Additionally, you are welcome to offer project comments.
